---
- name: Install Nginx
  hosts: jenkins
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx
      apt:
        name: nginx
        state: present
        
    - name: Enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started