apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-argocd
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "argocd.sallystore.my.id"
  http:
  - route:
    - destination:
        host: argocd-server.argocd.svc.cluster.local
        port:
          number: 80
