apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-elastic
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "elastic.sallystore.my.id"
  http:
  - route:
    - destination:
        host: elasticsearch-master.logging.svc.cluster.local
        port:
          number: 9200
