apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-grafana
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "grafana.sallystore.my.id"
  http:
  - route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
        port:
          number: 3000
