apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-kiali
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "k.jalanteknologi.id"
  http:
  - route:
    - destination:
        host: kiali.istio-system.svc.cluster.local
        port:
          number: 20001
