apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-kubesphere
  namespace: kubesphere-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "cicd.sallystore.my.id"
  http:
  - route:
    - destination:
        host: ks-console.kubesphere-system.svc.cluster.local
        port:
          number: 80
