apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-rancher
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "rancher.sallystore.my.id"
  http:
  - route:
    - destination:
        host: rancher.cattle-system.svc.cluster.local
        port:
          number: 80
