apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-vault
  namespace: istio-system
spec:
  gateways:
  - istio-system/istio-ingressgateway
  hosts:
  - "v.jalanteknologi.id"
  http:
  - route:
    - destination:
        host: vault.vault.svc.cluster.local
        port:
          number: 8200
