---

- name: Install Jenkins & Nginx
  hosts: tools
  become: true
  vars:
    jenkins_port: 8080


  tasks:
    - name: Update apt
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - openjdk-17-jre
          - nginx
          - certbot
          - python3-certbot-nginx
          - apt-transport-https
          - gnupg
          - wget
          - curl
          - git
        state: present

   # Install Jenkins
    - name: Download Jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present
        filename: jenkins

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes
    
    - name: start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
    
    - name: Wait Jenkins available
      uri:
        url: http://localhost:{{ jenkins_port }}
        status: 200
      register: result
      until: result.status == 200
      retries: 30
      delay: 10
      ignore_errors: yes

    - name: Get Jenkins initial admin password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_password
      changed_when: false

    - name: Display Jenkins initial admin password
      debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"