apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: token-updater-role-kiali
  namespace: istio-system
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]