# kalo udah patch deployment istio-ingressgateway dan apply envoyfilter, baru apply ini
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-from-whitelist
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway  # Label yang sesuai
  action: ALLOW
  rules:
  - from:
    - source:
        remoteIpBlocks:
        - "15.235.163.196"  # IP yang di-whitelist

    to:
    - operation:
        hosts:
        - "p.jalanteknologi.id"  # host yang mau lu whitelist